### ISSUE TITLE
Draft, Collect Feedback, and Publish Bounty Program guidelines and context

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#210]

**Comment by andrewg-xyz** [comment]
Drafting [here](https://docs.google.com/document/d/1Qc4FQfCSWqVFBkiBSzJb62mNWJaf9KLlrF-Y7_-tuyk/edit)

**Comment by jonnyborbs** [comment]
I spaced on updating this; bounty program is published and launched 

Coda: **https://coda.io/d/_dGmk3eNjmm8/2024-App-Integration-Bounty_subYSOZo**
Biweekly office hours every other Tuesday
