### ISSUE TITLE
Update - Top Navbar Logo and App name

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-marketplace#220]
## Issue

Rob gave some feedback regarding the icon size and way the app name was sytled. 

## Update

- [ ] Change doug icon to new size 56x56 px.  (i think tailwinds class is 14) but the file has the SVG logo in the right size
- [ ] Change the font style for "UDS Marketplace" to all be text-2xl-font-normal

### Additional context
Figma dev link https://www.figma.com/design/1xQF8rcaVAbJXcQxXal0RS/UDS-Marketplace?node-id=6122-41099&m=dev
<img width="425" alt="Screenshot 2024-09-20 at 11 18 54 AM" src="https://github.com/user-attachments/assets/6b7aff48-208c-4160-9712-47c3aa1084a4">

**Comment by andrewg-xyz** [comment]
![image](https://github.com/user-attachments/assets/0b88e23a-823a-4b7e-a5cb-57a68da1def6)
