### ISSUE TITLE
Identify a hosting solution for UI, to be accessed at apps.defenseunicorns.com

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#69]
Create an Architecture Decision Record on how we will host MVP of UDS marketplace.

**Comment by marshall007** [comment]
@andrewg-xyz I think hosting the frontend out of an S3 bucket is a good short term _and long term_ solution. If we try to host in Kubernetes day-one we have to build out CI/CD around that too. Even in the future, when we have a functional backend, hosting the frontend assets out of S3 reduces load off the API server and gets us things like DDoS prevention, global CDN, and overall better performance for free.

If we care at all about SEO, we're going to need server-side rendering for the site to be indexed properly. That means running a Node.js server, probably on AWS Lambda, Cloudflare Workers, Google Cloud Run, etc.

Point being, I don't forsee any scenario where it makes sense to host the FE out of K8s. If we want to get fancy, I'd pick one of those "cloud function" providers and use the tooling built into SvelteKit for deployment (https://kit.svelte.dev/docs/adapter-auto). If we don't want to get fancy, let's just host out of S3/GCS/Cloudflare.

**Comment by andrewg-xyz** [comment]
@marshall007 Thanks for your thoughts :) I agree with the logic of all of it. We may leverage S3 or another solution you mentioned long term.

In the short term, we need to lead with UDS and doing this solves more problems than it creates across Defense Unicorns.
- portability: deploying a uds-marketplace zarf package to UDS (UDS-core/k8s) ensures portability.
- - Marketplace has the potential to be deployed in many environments/customer bases. Even if our primary and initial deployment is "apps.defenseunicorns.com"
- Mission Ops experience: this team can be responsible for support of the environment and build out their experience which contributes to our effectiveness on the Unicorn Guarantee
- True dog-fooding, I disagree with the "right tool for the job" when UDS has an equivalent solution.
- Growth can stand up the environment and give them experience of reality of what we do in their conversations.

I'm happy to change direction or the solution in the future, but for the near term want to lean in on UDS.
